export { default as Teacher } from "./teachers/Teacher";
export { default as Student} from "./students/Student";
export { default as StudentsList } from "./students/StudentsList";
export { default as NewStudent} from "./students/New";
export { default as EditTeacher} from "./teachers/Edit";
export { default as EditStudent} from "./students/Edit";
export { default as NewTeacher } from "./teachers/New";
export { default as TeachersList } from "./teachers/TeachersList";
export { default as Transactions} from "./transactions/Transactions";
export { default as Homepage } from "./homepage/Homepage";
export { default as Login} from "./login/Login";