export { default as Product } from "./product/Product";
export { default as User } from "./user/User";
export { default as ProductList } from "./product/ProductList";
export { default as NewProduct } from "./product/NewProduct";
export { default as EditProduct } from "./product/EditProduct";
export { default as EditUser } from "./user/EditUser";
export { default as NewUser } from "./user/NewUser";
export { default as UserList } from "./user/UserList";
export { default as Orders } from "./orders/Orders";
export { default as Homepage } from "./homepage/Homepage";
export { default as Login} from "./login/Login";